root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "cd /jssrc && npm run build && rm -rf /go/src/config-tool/pkg/lib/editor/static/build && mv /jssrc/static/build /go/src/config-tool/pkg/lib/editor/static/build && cd /go/src/config-tool && go build -o ./tmp/main ./cmd/..."
# Binary file yields from `cmd`.
bin = 'tmp/main editor --config-dir=/conf --password=password'
# Watch these filename extensions.
include_ext = ["go", "js", "html", "toml", "json", "yaml"]
# Ignore these filename extensions or directories.
exclude_dir = ["pkg/lib/editor/static/build", "pkg/lib/editor/node_modules"]

# Watch these directories if you specified.
include_dir = []
# Exclude files.
exclude_file = []
# This log file places in your tmp_dir.
log = "air.log"
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Stop running old binary when build errors occur.
stop_on_error = true
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false
# Delay after sending Interrupt signal
kill_delay = 500 # ms

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true